### PR TITLE
Add chat replay timestamp option

### PR DESCRIPTION
**Pull request by MergHQ**
Implements issue #1062

So I'm not really sure if it is better to create a new CSS file and load it to the DOM, or use a event listener and change the display style property for each chat line.

### CODE REVIEW

**Comment by EhsanKia** [comment]
Chat already has a built-in "show time-stamp" option. Can we just re-use that instead of making YET another option in the settings menu? I realize you don't get the cogwheel in the chat replay so you can't toggle it while watching a VOD, but anyone who cares about timestamps will have it enabled for chat, and will therefore get it also in replays. I don't see why'd you would want it in one and not the other.

Here's how to access the setting:
`Twitch.storage.getObject('chatSettings').showTimestamps`

**Comment by MergHQ** [comment]
I didn't know you could get twitch user settings, thanks for showing me. I'll make the changes.

**Comment by night** [comment]
I don't like loading one line CSS files. How about adding a show-timestamp class to chat lines as they render with our pre-existing chat replay logic?

**Comment by MergHQ** [comment]
Sounds good. I'll do that.

**Pull request closed without merging**
