### PR TITLE
Added MTGBot back to the bot list.

### PR DESCRIPTION
**Pull request by danbopes**
I fixed the spacing issues. MTGBot will be the primary bot in all magic channels, and hopefully start making it's way into the hearthstone channels as well. I'd like it show up as a bot as it once did a year ago.

### CODE REVIEW

**Comment by danbopes** [comment]
Sorry, I just saw your post back in the other thread. Can I ask why you're not willing to add this to the global bots list @night ? I really hate to go to 200 channel owners and tell them if they want it to look nice, they have to manually add this bot to the list.

This was once a global bot, and is still maintained to this day with a fully functional website (http://mtgbot.tv) with similar features to xanbot/moobot, owned by me, and no one else. This name will not be changing, and I don't see a reason for exclusion from the global bot list.

**Comment by night** [comment]
As stated,

> We're not adding additional bots. Channels can add your bot to their channel bots list at https://manage.betterttv.net

**Comment by danbopes** [comment]
@night Custom bots are one thing with custom names, and I can understand the need for channels to maintain their own list, but I believe the main bot list should be used for bots that aren't changing names, and are in a significant number of channels.

Some broadcasters don't do any research, nor care besides typing '!join' in a channel to get a bot to join. It's just an eye sore to see bots such as Xanbot or Moobot have a nice bot icon, and then Mtgbot to have a sword icon by the name. Most broadcaster will not care, or just ignore this, and for everyone else in the channel it's something they just have to put up with.

I strongly ask that you reenable this functionality so that I don't have to goto 150 broadcasters and advise them on how to set this up.

**Comment by night** [comment]
We made channel bot lists because we do not want to maintain a bots list. If a broadcaster wants their bot to have a status symbol in chat they can add it as a channel bot.

We were tired of people asking to give their bot a bot tag, so this is our solution. We won't be making exceptions to this policy because again, we're not maintaining a bot list. The three largest bots are well known on Twitch, and they will remain for the time being. It's possible they will eventually be removed too.

**Comment by danbopes** [comment]
That's a shame. It was a cool feature, but it's going to get completely underutilized/not utilized at all at this point. I think if you're going to go with this route, just remove the functionality all together. Having some have half-assed system for enabling the bot icon is quite frustrating, as it will show in some channels, but not others.

**Comment by night** [comment]
> Having some have half-assed system

¯\\_(ツ)_/¯

**Comment by danbopes** [comment]
> ¯\(ツ)/¯

I apologize for that terminology, but I think for the focus of non custom bots, that a global solution would work better for people like me. Asking several hundred broadcasters to add a setting so that the bot can look prettier in their channel, I think would be a sub-optimal solution. Asking the bot owner that he custom created for his channel to add it to the bot list if he wants it to show nice in his channel, is another thing entirely. I'm not going to be seeing his custom bot in another channel, which would mean I wouldn't see a bot "icon" in one channel, and a mod "icon" in another.

Here's a possible solution, that I think would work well:

How about making it so in your panel, having a certain number of users add it to their bot list, it would be considered a global bot. That way, when the bot starts gaining popularity, it would automatically be added to the global chain so future broadcasters wouldn't have to add it manually.

**Comment by Fire-** [comment]
> Asking several hundred broadcasters to add a setting so that the bot can look prettier in their channel, I think would be a sub-optimal solution. Asking the bot owner that he custom created for his channel to add it to the bot list if he wants it to show nice in his channel, is another thing entirely. 

They're the same thing. Where would you otherwise draw the line? 5 channels? 10? It's not a maintainable solution, so not doing it at all is the better solution. Keep in mind:

> The three largest bots are well known on Twitch, and they will remain for the time being. **It's possible they will eventually be removed too.**

Emphasis mine

-----

> How about making it so in your panel, having a certain number of users add it to their bot list, it would be considered a global bot. That way, when the bot starts gaining popularity, it would automatically be added to the global chain so future broadcasters wouldn't have to add it manually.

This is far too easy to game

**Comment by danbopes** [comment]
Please remove nightbot, moobot, and xanbot from the list of global bots, like your comment suggested @night or please merge this commit in.

**Comment by vendethiel** [comment]
Great way to go about it, people usually like this sort of behavior.

I love open source.

**Comment by danbopes** [comment]
I have tried being nice about it, offering a donation in order to my bot added in, and I'm dealt with the frustration of having to tell each and every one of my users how to add MTGBot as a bot. Frankly, it's quite tiring, and I'd like @night to follow through with his word about removing the other bots to keep them all at the same playing field, or kindly add mtgbot back to the list.

**Comment by night** [comment]
@danbopes https://www.youtube.com/watch?v=2k0SmqbBIpQ

**Pull request closed without merging**
