### PR TITLE
#yolo

### PR DESCRIPTION
**Pull request by matthewjk123**
Fixed the Teespring Campaign T-Shirt box for partners under Affiliate options

### CODE REVIEW

**Comment by DTittel** [comment]
Code looks fine. Is it just the one commit or do you have more (#yolo doesn't tell me much)

**Comment by matthewjk123** [comment]
@DTittel Yeah that's it. If you read what I put, it just fixes the campaign thing for T-Shirts :D

**Comment by DTittel** [comment]
Ya I know, just making sure you weren't planning on tacking on any other commits before I merged it.

**Comment by matthewjk123** [comment]
@DTittel Yeah nps. I'm looking through twitch to see if anything needs fixing or tweaking. But I'm off to bed now. I'll check more tomorrow.

**Pull request merged**
