### PR TITLE
Enhanced mod card

### PR DESCRIPTION
**Pull request by EhsanKia**
This is partly a solution to #257 

It doesn't do following count, but it does add followers and channel views count (which come for free).
Not sure if "following" is worth an extra request, but I can add it if you think it is.
I also considered adding account creation date, but I didn't want to clutter the interface too much.

Here is what it looks like:
 

There's also a background image bug which I fixed in a separate commit:

### CODE REVIEW

**Comment by night** [comment]
While the green color you chose for the font looks great for your profile background, it would not for all colors. You should change the color to be more appropriate for all users.

**Comment by EhsanKia** [comment]
I didn't really choose the green hue to match my BG, it just looked bad being the same color as `real-name`. Maybe a yellow-ish hue will look more neutral?

**Comment by OurFlagIsMined** [comment]
The dark yellow text does look pretty nice.

The 'following' count could go either way; would be nice to have there, but for at-a-glance stats, 'followers' and 'views' are much more useful (very useful!) given limited space. You might be able to fit it by right justifying the third stat, but then it may start to be information overkill.

Account creation date, I would omit all together. Many of the newer message boards don't even display that information because it adds very little and doesn't mean all that much.

**Comment by EhsanKia** [comment]
I actually would disagree. As a mod, I use account creation a lot to find fake/troll accounts that were made on the spot. I would even argue that it's more useful than channel views, which generally gives the same amount of information as follower count.

**Comment by OurFlagIsMined** [comment]
In that case, maybe a flag (metaphorical or literal) in the corner, if the account is less than 1 week old?
temp-temp-temp-mod_card_flag-01

**Comment by night** [comment]
I think we need to put the exact date an account was opened, which would look better than a flag. A *lot* of people want account creation date to shown, so that cannot be omitted.

**Comment by EhsanKia** [comment]
Sounds good to me. I think you guys are under a transition to SASS, and since this plays a lot in the CSS, I guess I should wait for that to be over.

**Comment by DTittel** [comment]
You could just write a _modCard.sass if you want :D

**Comment by night** [comment]
@EhsanKia You can again just commit these changes now, and I'll merge them. We're still making plans for style and settings refactoring, and rather than keeping these pull requests open for a long period of time they might as well be merged in.

**Comment by OurFlagIsMined** [comment]
On second thought, following count might be a really useful tool too for weeding out troll accounts. Might be worth that extra API request.

**Comment by EhsanKia** [comment]
Sorry for the delay on these pull requests. My ISP screwed me over and I was left without internet for a week. I'll fix these up real soon.

**Comment by EhsanKia** [comment]
New design, to fit the extra information:

 

 

Currently, hovering on views/follows doesn't show a tooltip though (like under the stream).
Haven't looked into how complicated it'd be, not sure if it's worth it.

**Pull request merged**
