### PR TITLE
[new-twitch] Add tab completion on tab key press.

### PR DESCRIPTION
**Pull request by DayBr3ak**
It's kind of a duplicate of #2819 except it's a different implementation and supports Emojis. This PR removes the acual twitch suggestions and implement it like the old twitch web site did (on tab key press)

### CODE REVIEW

**Comment by thinkpad4** [comment]
Any way to remove the suggestion box?

**Comment by DayBr3ak** [comment]
I'm sorry I wasn't clear enough. This PR disable the suggestion box, you can only rotate through names with the tab key.

**Comment by thinkpad4** [comment]
PERFECT!

**Comment by DayBr3ak** [comment]
I've merged this branch into #2819 
closing

**Pull request closed without merging**
