### PR TITLE
Adding Scrollbars to Whispers

### PR DESCRIPTION
**Pull request by Aaron128l**
Also added support to whisper emote menu.

### CODE REVIEW

**Comment by night** [comment]
scrollbars weren't already a thing?

**Comment by EhsanKia** [comment]
The problem is we have to add the custom scrollbar CSS for every new scrollbar. I think honestly we can just apply that to every single scrollbar on the site and be fine. The custom scrollbar looks good.

**Comment by night** [comment]
oic.. well I don't think global css is the right idea since twitch might also use these scrollers on rails pages, which would break.. prefer to keep things whitelisted

**Comment by night** [comment]
resolve the conflicts and I can merge

**Pull request merged**
