### PR TITLE
Feature #141

### PR DESCRIPTION
**Pull request by Naththo**
#141

### CODE REVIEW

**Comment by vendethiel** [comment]
This is the wrong file to change. You need to change the files in `src/` and use `gulp watch` to watch your files and rebuild on change.

**Comment by vendethiel** [comment]
tip n2 : you can just commit and push and github will pick it up

**Comment by Naththo** [comment]
Okay, I'll take a look again. My bad.

**Comment by Naththo** [comment]
@vendethiel Can you check this please? https://github.com/Naththo/BetterTTV/commit/679d0d9eb5d5cace1afe9ee616c9eb866cf3d583

**Comment by night** [comment]
@Naththo You need to work on your tabs, as we tab with spaces not actual tabs.

Also, this type of spam isn't actually ASCII spam, as ASCII is only characters < 128: https://i-msdn.sec.s-msft.com/dynimg/IC102418.gif You should rename this to what it is: unicode symbol spam.

**Comment by Naththo** [comment]
Okay, thank you night.

I'll do this sometime tomorrow.

**Comment by Naththo** [comment]
Sorry about the delay @night 
https://github.com/Naththo/BetterTTV/commit/562e5df9be6e27e563acaad9d2d7aedf4e9e4da9

If it's good I'll create a PR.

**Pull request closed without merging**
