### PR TITLE
Added timestamps to notification messages: Fixes #291

### LINKED ISSUE #291: time stamps for notifications
Add time stamps for chat notifications when time stamps are enabled in twitch settings like:
- welcome message
- subscription
- host started
- host stopped
- timeout
- ?

### PR DESCRIPTION
**Pull request by amamut**
Notification messages are now tied to the time stamp option in the settings panel. Also added an added override within to code to force time stamps to be disabled because sometimes you don't want them. (e.g. BTTV version load message).

timestamp message

### CODE REVIEW

**Comment by night** [comment]
I'm not liking this implementation, as the extra argument to toggle timestamps off seems superfluous. ```date``` is already an object key, so you should be setting that to null if date isn't wanted.

**Comment by amamut** [comment]
@night With the current implementation all server messages hide the timestamp. I thought that the "loaded" messages didn't really need a timestamp and looked weird with it. So I added a way to suppress the timestamp. This had minimal impact on existing code. I can make a separate server message call which will suppress timestamps if you'd like. Or just remove the override all together.

**Comment by night** [comment]
I am all for hiding timestamps for messages like the loaded message, but I do not think there should be an additional argument added to the function.

The code should be modified to instead show dates only when a date is seen in the message object. You can then append a message that is printed with a hide timestamps class if the date isn't in the message object.

This seems like a more correct way of doing things.

**Comment by amamut** [comment]
@night I can make the change you requested but the reason why I did it this way is because I believe that the "BTTV Loaded" message is the only message which is formatted uniquely to where the time stamp looks bad. So it was easier to add a bool to that call instead of looking through all of the code and adding a Boolean to ALL serverMessage calls.

**Comment by amamut** [comment]
I've made the updates but I've noticed that Twitch may have updated their chat because all BTTV chat commands come back with BTTV response AND another message saying "Unrecognized command". I will have to see if I can disable these messages.

**Comment by night** [comment]
Those messages happen because BetterTTV passes through our custom commands to the Twitch chat server. Twitch used to not return errors when a command did not exist.

**Comment by amamut** [comment]
@night Ok thanks for the heads up. I disabled internal bttv commands from being sent to the twitch chat servers.

**Pull request merged**
