### PR TITLE
Better viewer list

### PR DESCRIPTION
**Pull request by EhsanKia**
Initial implementation of my custom viewer list.
It doesn't fuck with Ember at all, so it shouldn't break easily.

### Features
- Filtering: https://gfycat.com/DecentRepentantEasternglasslizard
- Drag / Resize:  https://gfycat.com/ExcitableLongFlicker
- Refresh (and restore old list on failure): https://gfycat.com/DeliciousEnormousHamster
- BTTV moderation cards: https://gfycat.com/UnknownMeaslyFlyingfish

### Extra detail
- it locks the refresh button for 30s after successful load (might increase that)
- It depends on 2 npm packages: [view-list](https://www.npmjs.com/package/view-list) and [resizable](https://www.npmjs.com/package/resizable) (could maybe get rid of resizable)
- No performance issues, even at 100k+ viewers
- Slight change to mod card positioning (use cursor instead of hardcoded chat position)

Still needs some testing as there are a lot of edge cases to check,
but so far from my testing, it seems very usable.

Any thoughts?

### CODE REVIEW

**Comment by thinkpad4** [comment]
EhsanKia, I really like this.  The search really helps in those large streams when you need to find someone quick

**Comment by night** [comment]
remind me in a week to review this PR, too busy atm

**Comment by EhsanKia** [comment]
Do you have some more free time now?

Do note that it's obviously a toggle option, and it's off by default, so any issues will hopefully have a smaller impact. It'll be useful to have it out and used by a few people so I can iron out any rare bugs that might creep up. Could maybe even not include it in the settings list yet and have people we know toggle it manually during a "beta" phase through console.

**Comment by night** [comment]
> Do you have some more free time now?

will get to it when I get to it.. still too busy.

**Comment by night** [comment]
@EhsanKia can you rebase

**Pull request merged**
