### PR TITLE
fixed progress-bar width so it aligns correctly

### PR DESCRIPTION
**Pull request by cenderin**
Teak commented about this on [#246](https://github.com/night/BetterTTV/issues/246#issuecomment-75452070)

### CODE REVIEW

**Comment by DTittel** [comment]
Lol seems like this patch is more about removing trailing whitespace than the progress bar width. Code looks fine but haven't tested it out.

**Comment by cenderin** [comment]
yea... It's automatic normally, maybe I should turn it off when i'm doing stuff like this.

**Comment by teak** [comment]
Tested. Looks good..

**Comment by vendethiel** [comment]
You can just append ?w=1 after the URL to get a whitespace-free changeset.

**Pull request merged**
