### PR TITLE
GameWisp emotes

### PR DESCRIPTION
**Pull request by TJBIII**
Adds GameWisp global and subscriber emotes.

I can provide login details for test Twitch accounts that have access to GameWisp subscriber only emotes to make reviewing this simpler. Just let me know where to send the info.

### CODE REVIEW

**Comment by night** [comment]
thanks for the PR. I will review this soon.

**Comment by night** [comment]
Apologies for the delay. We're actually amidst a bit of a rewrite to address some larger issues with extension stability. If you don't mind we can hold this until then, or we can merge it now and it will need to be updated upon the release of the new version.

**Comment by TJBIII** [comment]
We would like to get it in before the rewrite if possible and then will update for the new version. We're going to ramp up some of the supporting infrastructure over the next few days and then I'll be in touch later this week when everything is ready. Thanks!

**Comment by TJBIII** [comment]
All good on our end. This can be merged and go live at your convenience.

**Comment by night** [comment]
Hate to be that guy, but if you could rebase your changes off of the v7 branch and rebuild your PR to it instead that would be helpful. We're hoping to have v7 out within the next week.

**Comment by TJBIII** [comment]
Closing in favor of #2131 for v7.

**Pull request closed without merging**
