### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by NBruderman**
All updated to the latest stable version

### CODE REVIEW

**Comment by night** [comment]
build fails

**Comment by NBruderman** [comment]
The problem was with the "gulp-enlist" update (3.0.1 -> 4.0.0).
I reverted it, and everything is working fine again.

**Comment by night** [comment]
you should fix the underlying issues rather than revert to an old version

**Comment by NBruderman** [comment]
Can you help me solve that?
this is the error I get

> [19:59:08] Using gulpfile ~/build/night/BetterTTV/gulpfile.js
> [19:59:08] Starting 'cleanup'...
> [19:59:08] Starting 'lint'...
> [19:59:08] Finished 'cleanup' after 22 ms
> [19:59:10] 'lint' errored after 2.05 s
> [19:59:10] ESLintError in plugin 'gulp-eslint'
> Message:
>     Expected indentation of 12 spaces but found 8.
> Details:
>     fileName: /home/travis/build/night/BetterTTV/src/modules/chat_link_preview/index.js
>     lineNumber: 53

Should I just catch that exception?

**Comment by NBruderman** [comment]
Nevermind, found the issue.
All is ready and working.

**Comment by Aaron128l** [comment]
`/* eslint-disable indent */` isn't needed in both places you added it. Simply indent the areas that are failing.

**Comment by NBruderman** [comment]
@night It's ready now... unless you want me to make a cleaner pull request

**Pull request merged**
