### PR TITLE
Update window title to reflect stream title

### PR DESCRIPTION
**Pull request by EhsanKia**
Very simple commit for #290, just a single line.
Feel free to change the formatting.

### CODE REVIEW

**Comment by night** [comment]
Please read the README.md before submitting a pull request.

Additionally, this is not a good solution. This should be a toggleable option, and you should be limiting the length of the title.

**Comment by EhsanKia** [comment]
By option, do you mean full on button in the settings page? That seems overkill for such a small "feature". Or just a setting that can be toggled through console, similar to consoleLog?

**Comment by night** [comment]
Because this impacts a small space's functionality and we don't want complaints, it needs a setting toggle.

**Comment by OurFlagIsMined** [comment]
I agree that it needs to be a setting, since the clean interface and titles are part of what makes Twitch such a user friendly site; and in my opinion one that's disabled by default since it adds a lot of clutter to the title, and would make bookmarked streams save with inconsistent names.

I do think however that it would be welcomed by a lot of people if it did so for VODs, since each VOD is a unique bookmark, and would allow searching by stream title.

**Comment by EhsanKia** [comment]
You guys make the call, and I'll code it. Honestly this was mostly me getting my feet wet by taking on some smaller feature request, so I don't mind if it gets scratched for now.

Maybe wait for the new settings page? I'm not sure what kind of features you guys are planning for that, but [something like RES](http://i.imgur.com/7mYnlpv.png) seems like the better platform. Then we can hide this somewhere deep in the UI setting hierarchy.

Right now, settings are just a bunch of big buttons, and already as is, I always have a hard time finding the one I'm looking for, adding more small ones like this would just make it worse.

But yeah I'm happy to code whatever.

**Comment by night** [comment]
We are working on a new settings system (@teak is still designing the interface), but there's not really an ETA on when it might be done. If you want to add in the setting now, go for it. Otherwise you might be waiting a while.

**Comment by night** [comment]
@EhsanKia I would just go ahead and just add a setting for this now, and we'll refactor settings down the road.

**Pull request closed without merging**
