### PR TITLE
Add option to hide the purple squadstream bar above the player

### PR DESCRIPTION
**Pull request by chrisheib**
See Issue #3424
Just a simple implementation without much fuzz. 
My first contribution here, if there is something to be noted please tell and I will improve.

### CODE REVIEW

**Comment by chrisheib** [comment]
Urg, this needs some further improvement, it seems to also kill some other icons.

**Comment by chrisheib** [comment]
Now it should only be affecting the correct bar.

**Comment by night** [comment]
Apologies for the delay in response. Your CSS selector does not look specific enough to classify just the squad stream bar. Because of this, it is possible you may mistakenly hide some other element with a similar pattern of animation implemented.

**Comment by night** [comment]
it looks like twitch has made this less intrusive, so this is no longer needed

**Pull request closed without merging**
