### PR TITLE
Theatre Mode shortcut

### PR DESCRIPTION
**Pull request by kallebornemark**
Extended `Player Keyboard Shortcuts` setting by adding shortcut ("*T*") for Theatre Mode.

### CODE REVIEW

**Comment by EhsanKia** [comment]
Doesn't alt+t already do theater mode? That's part of Twitch itself.

**Comment by night** [comment]
It does. We need not reimplement what's implemented already.

**Comment by kallebornemark** [comment]
Urm, so what is the point of this setting? All of the keybinds it includes are already available at alt+key.

**Comment by night** [comment]
They definitely are not.. The only other alt key for the player is alt+x for clipping

**Comment by kallebornemark** [comment]
Oh, I see my confusion now. Having the setting enabled also allows one to use its keybinds with the alt modifier, making me believe alt+key existed for all of the features (mute, pause, etc). And even though I would much prefer "T" over "alt+T", I fully understand the choice of not implementing it. Sorry about the fuzz!

**Pull request closed without merging**
