### PR TITLE
Whisper Feedback

### PR DESCRIPTION
**Pull request by OurFlagIsMined**
Added an option to play the tink sound on incoming whisper.

#492

### CODE REVIEW

**Comment by night** [comment]
Do you think we need an extra option for this? Would grouping it with the other highlight sound option be more appropriate? Thoughts?

**Comment by cletusc** [comment]
IMO highlight sound should cover both.

**Comment by OurFlagIsMined** [comment]
I changed it to one setting for both, and whisper feedback now also displays the visual notice box if desktop notifications are enabled and if the window is inactive.

I originally gave it two settings because of the difference in the way highlight feedback and whisper feedback work. Highlight feedback only plays if desktop notifications are turned on and the window is inactive; whereas the desired behavior for whisper feedback is simply to play a tink for every whisper received, even when the window is active.

If you're watching with chat hidden, or leave the window open while you walk away for a minute, or simply aren't paying attention to chat, you would miss the whisper if audio feedback were tied to desktop notifications and window activity the way highlight feedback is. And whispers are more like PMs than highlighted messages, but if you miss them once they're gone.

Personally I think even the highlight feedback is kind of obscure to use this way, and I don't know of any other chat client that only plays its audio feedback if the window is inactive, but I didn't think it was important to bring up or suggest changing for now as long as whisper audio feedback works the way it should.

temp-temp-temp-git_betterttv_whisper_notice-01

**Comment by night** [comment]
If you change the storage key, you break everyone's settings since the feature is off by default. You should remain with the ```highlightFeedback``` storage key.

**Comment by OurFlagIsMined** [comment]
Fixed.

Tunnel vision; I noticed it getting reset during testing, but forgot it would reset the setting for everyone else too.

**Comment by night** [comment]
Looks good

**Pull request merged**
