### PR TITLE
Regex Highlighting

### PR DESCRIPTION
**Pull request by rue92**
This includes my modifications in order to support regular expression highlighting for messages as per Issue #267 which I created in March. It's nothing fancy, but I figure most people have no desire to use JS regular expressions so I included the option to turn it on/off. Otherwise, I made it so the user has to delimit their regular expression with semicolons, but can otherwise treat it like a regular highlight keyword -- it's not the greatest, but it worked. 

Comments, criticisms, etc. welcome. Thanks.

### CODE REVIEW

**Comment by night** [comment]
Hi, this is an interesting pull request. Is there a reason you're using semicolons and not forward slashes? Forward slashes are typically used to denote regex and may better fit for this application.

Additionally, there's a large worry users will lock up their page with a bad regex. You may want to wrap the user input in an atomic group so the regex will return quickly: http://www.regular-expressions.info/atomic.html

**Comment by rue92** [comment]
Semicolons as opposed to forward slashes was really a choice I made before I put the settings in to enable/disable regular expressions. Otherwise, I agree forward slashes are the well established convention, and I'll make the change appropriately.

As for atomic groups, that's a new concept to me (the struggles of a novice programmer :P), but I can see the need so I'll take a look and figure something out. Thanks for the help!

**Comment by rue92** [comment]
I've made the delimiter change, however, according to http://www.regular-expressions.info/javascript.html and my own verification, JS doesn't support atomic groups. I'll leave it up to your discretion whether you take the request with that information.

**Comment by ar664** [comment]
Would it be possible to use this for Blacklisting as well?

**Comment by rue92** [comment]
Sorry for very late response, @ar664. Definitely can be done, and it would make for a great excuse to refactor the code to make it cleaner in both hilighting and blacklisting. 

Only thing is, and I understand the concern by the maintainer, that there isn't an obvious way to keep a user from defining a regex that locks up their browser. On that note, I wonder if there's a way to wrap the regex match with a timeout of some sort? I'll have to investigate.

**Comment by night** [comment]
Found this lib on npm that might allow regexes to be used: https://www.npmjs.com/package/safe-regex

If we can check that all (or at least most) regexes are safe before saving them (or I guess executing them) it might be safe enough.

**Comment by ar664** [comment]
I looked around and I found this site to possibly generate new regexp to test. 
http://txt2re.com/index-javascript.php3?s=11:May:2016%20%22This%20is%20an%20Example!%22&7

Maybe you can do some sort of brute force method to see the avg run-time / exp-failures of the given expressions.

**Comment by night** [comment]
The concern is not a predefined set of expressions, but rather any expression a user enters. Users who don't understand need to be safeguarded, which is why the package I linked may work for this use-case. Piping regexes into a web service to get a run time is not a good solution here, nor is it something we could accomplish locally in JavaScript due to how JavaScript executes regexes (they cannot be stopped early).

**Comment by ar664** [comment]
Are you running linux? It is possible to kill a process beyond a threshold time using scripts, but I understand the reasoning behind why you wouldn't want to get pre-generated regex's. The only question I have is how you would got about testing the safe-regex for viability? 
My method is crude, but its a little better than randomly generating strings because I believe safe-regex tests for whether the expression is one of regex.

**Comment by rue92** [comment]
I think there's a little confusion here.  It sounds like ar664 is suggesting we test safe-regex (which is a great find by the way) ourselves with a few crafted degenerate cases to verify it. I'm alright with doing this and I can try to tackle it this week/weekend as well as make the changes I promised way back when. How does that sound?

**Comment by ar664** [comment]
@rue92 Yes, That is exactly what I'm trying to say thank you. @night Also, I'm sorry if I sounded ignorant or rude before English is my second language, so I tend to not give tone appropriately in writing.

**Comment by night** [comment]
> I think there's a little confusion here. It sounds like ar664 is suggesting we test safe-regex (which is a great find by the way) ourselves with a few crafted degenerate cases to verify it. I'm alright with doing this and I can try to tackle it this week/weekend as well as make the changes I promised way back when. How does that sound?

That works fine. Just do note you need to also rebase your fork from master because it's severely out of date.

**Comment by night** [comment]
closing this pr due to inactivity. open a new pr if you address the issues.

**Pull request closed without merging**
