### PR TITLE
Add new feature #996

### PR DESCRIPTION
**Pull request by MergHQ**
Direct link to audiotwitch.tv under the video player.

### CODE REVIEW

**Comment by night** [comment]
AudioTwitch doesn't seem to work..

**Comment by MergHQ** [comment]
That's weird. I'll tweet them and ask what's up.

**Comment by samfun123** [comment]
A optional replacement would be [radiotwitch.in](http://radiotwitch.in/) which seems to be working.

**Comment by MergHQ** [comment]
Okay. It's now using radiotwitch.in.

**Comment by night** [comment]
Meh. I definitely am not a fan of this integration. I'd rather have something that embeds an iframe over Twitch's player and looks a lot nicer/modern. A popup window isn't really a native implementation that makes sense.

**Comment by MergHQ** [comment]
I can't use iframes because radiotwitch uses http and not https. Therefore this feature cannot be implemented.

**Comment by night** [comment]
Sorry for the late response. You might try reaching out to either of these sites to ask if they would add ssl support. Many might be willing. ¯\\_(ツ)_/¯

**Comment by Zalatis** [comment]
Atm radiotwitch and audiotwitch doesn't work :'( any others website who do the same job ?

**Pull request closed without merging**
