### PR TITLE
Regular Expression Highlighting

### PR DESCRIPTION
**Pull request by rue92**
Hey there,

Same old deal: PR to add regular expression highlighting for #267 after my last PR was closed (it's cool, I was lazy about getting it done :P). Anyway, I added the safe-regex package as suggested to deal with potentially browser-locking regexes. Curiously, I couldn't get Chrome or Firefox to lock up on an unsafe-regex like `(a+){10}` without it anyway, but, there are a multitude of bad regex's I agree should be avoided.

Hope this meets your expectations!

### CODE REVIEW

**Comment by thinkpad4** [comment]
Now when this is disabled highlighting will function as it always has, right Rue92?

**Comment by rue92** [comment]
Yup, that's the intention. Unless I've screwed up something which I don't
believe I did. :)

**Comment by thinkpad4** [comment]
You rock Rue92

**Comment by night** [comment]
I will review this over the weekend. Sorry for the delay.

**Comment by night** [comment]
so an edge case here is when people place links in their highlight list. this breaks for those users.

**Comment by rue92** [comment]
What do you think about backslashes or pipes then? Alternatively maybe we tack on square brackets, e.g. [/regex/]?

**Comment by EhsanKia** [comment]
I think we should allow only a single regex expression, as in, starts and ends with /
I think the current implementation allows for any number of regexes inside a single highlight expression?

Also, once that's in, I think we can even remove the option from settings menu.
I don't see anything inputting a highlight expression starting and ending with /

**Comment by night** [comment]
This PR is kinda dead again. Please address the issue with it and resubmit it again, I guess.

**Pull request closed without merging**
