### PR TITLE
Non-legacy Tab completion cycling

### PR DESCRIPTION
**Pull request by voloshink**
Tab to cycle through the suggestions

### CODE REVIEW

**Comment by vendethiel** [comment]
this is not the correct file to change – you're supposed to change files in the `src/` directory.

for the PR: is legacy tab completion cycling working? If so, then there's definitely some duplication here

@night Should we add a "GENERATED" warning header in the compiled .js file?

**Comment by voloshink** [comment]
Moved changes to the correct file.

**Comment by voloshink** [comment]
Yes, legacy tab completion also allows you to cycle through suggestions but the legacy and non legacy completion do it in different ways. This change lets the user cycle through the suggestions pop up after they enter @. It's a quality of life change. I'm sure both tab completions can be merged at some point.

**Comment by night** [comment]
Not needed any longer.

**Pull request closed without merging**
